name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # Install core package dependencies first
        pip install -r requirements-ci.txt --timeout=600
        # Install package in editable mode
        pip install -e . --no-deps
      timeout-minutes: 15

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short --maxfail=3 -x
      timeout-minutes: 20

    - name: Run linting
      run: |
        python -m ruff check omega_phr/ services/ tests/

    - name: Run type checking
      run: |
        python -m mypy omega_phr/ --ignore-missing-imports
